# Generated by Django 4.2 on 2024-03-15 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('name', models.CharField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('main_image', models.FileField(blank=True, max_length=256, null=True, upload_to='save_profile_image')),
                ('height', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('hair_color', models.TextField(blank=True, null=True)),
                ('eye_color', models.TextField(blank=True, null=True)),
                ('skin_color', models.TextField(blank=True, null=True)),
                ('dating_preference', models.TextField(blank=True, null=True)),
                ('interest', models.JSONField(blank=True, null=True)),
                ('face_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
