# Generated by Django 4.2 on 2024-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_profile_about_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eye_color',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_color',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.TextField(null=True),
        ),
    ]
