# Generated by Django 4.2 on 2024-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datingpreference',
            name='preference',
        ),
        migrations.AddField(
            model_name='datingpreference',
            name='female',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='datingpreference',
            name='lgbtq',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='datingpreference',
            name='male',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
