# Generated by Django 4.2 on 2024-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_remove_datingpreference_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datingpreference',
            name='female',
        ),
        migrations.RemoveField(
            model_name='datingpreference',
            name='lgbtq',
        ),
        migrations.RemoveField(
            model_name='datingpreference',
            name='male',
        ),
        migrations.AddField(
            model_name='datingpreference',
            name='preference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
