# Generated by Django 4.2 on 2024-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_profile_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='save_profile_image/images1'),
        ),
    ]
