# Generated by Django 4.2 on 2024-03-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_aboutsingles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSingles',
        ),
    ]
