# Generated by Django 4.2 on 2024-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_aboutsingles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacypolicy', models.TextField(max_length=512, null=True)),
            ],
            options={
                'db_table': 'privacy_policy',
            },
        ),
    ]
