# Generated by Django 4.2 on 2024-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
