# Generated by Django 4.2 on 2024-03-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_profile_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='map_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='radius',
        ),
        migrations.CreateModel(
            name='UserCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_active', models.BooleanField(default=False, null=True)),
                ('radius', models.CharField(default=5, null=True)),
                ('current_location', models.TextField(null=True)),
                ('current_coordinates', models.JSONField(null=True)),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'user_coordinates',
            },
        ),
    ]
