# Generated by Django 4.2 on 2024-03-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_adminuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_user',
        ),
    ]
