# Generated by Django 4.2 on 2024-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_alter_adminuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
