# Generated by Django 4.2 on 2024-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_alter_adminuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_status',
            field=models.CharField(default='active', null=True),
        ),
    ]
