# Generated by Django 4.2 on 2024-03-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_name',
            field=models.CharField(default='User', null=True),
        ),
    ]
