# Generated by Django 4.2 on 2024-04-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_profile_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role_name',
        ),
    ]
