# Generated by Django 4.2 on 2024-04-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_adminuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
