# Generated by Django 4.2 on 2024-04-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0036_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
