# Generated by Django 4.2 on 2024-04-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0038_alter_profile_about_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
