# Generated by Django 4.2 on 2024-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0039_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sample_height',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sample_weight',
            field=models.TextField(null=True),
        ),
    ]
