# Generated by Django 4.2 on 2024-04-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0040_profile_sample_height_profile_sample_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoordinates',
            name='current_location',
        ),
    ]
