# Generated by Django 4.2 on 2024-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0041_remove_usercoordinates_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(default='000000', max_length=6, null=True),
        ),
    ]
