# Generated by Django 4.2 on 2024-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0043_profile_verify_otp_alter_profile_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=256, null=True)),
                ('answer', models.TextField(max_length=512, null=True)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
