# Generated by Django 4.2 on 2024-04-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0044_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_blocked_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_blocked_profile', to='user_management.profile')),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_user_profile', to='user_management.profile')),
            ],
            options={
                'db_table': 'blocked_user',
            },
        ),
    ]
