# Generated by Django 4.2 on 2024-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0047_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'static_content',
            },
        ),
    ]
