# Generated by Django 4.2 on 2024-04-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0048_staticcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('report_about_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_report_about', to='user_management.profile')),
                ('reported_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_reported_by', to='user_management.profile')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
