# Generated by Django 4.2 on 2024-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0052_reports_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
