# Generated by Django 4.2 on 2024-09-09 09:02

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0053_reports_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=user_management.models.save_profile_image),
        ),
    ]
