# Generated by Django 4.2 on 2024-09-11 08:10

from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0054_alter_profile_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=user_management.models.get_default_role, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.role'),
        ),
    ]
