# Generated by Django 4.2 on 2024-08-13 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0053_reports_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plan_type',
            },
        ),
        migrations.CreateModel(
            name='PlanCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('charges_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('extra', 'Extra'), ('first_month', 'First Month')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('price', models.FloatField(max_length=20)),
                ('i_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_charges', to='subscription.plan')),
            ],
            options={
                'db_table': 'plan_Charges',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='i_plan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.plantype'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=50)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product_id', models.CharField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('i_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
                ('i_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'membership',
            },
        ),
    ]
